### ISSUE TITLE
デプロイが遅い

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/CommandReference#19]
天上天下唯我独尊 超完璧超ハイパープログラミング言語 Rust の唯一の欠点 **コンパイルが遅い** 

mdbook を自前でビルドをするのは愚かかも. バイナリをもらってくるのが一番頭がいいかもしれん.

https://github.com/GiganticMinecraft/CommandReference/blob/6faa82a601a5aa3cc85a79f67ffd21a96a262db2/.github/workflows/deploy.yaml#L27-L31

**Comment by m1sk9** [comment]
まああとはキャッシュさせるとか...?

**Comment by KisaragiEffective** [comment]
https://github.com/rust-lang/mdBook/releases から引っ張ってくるのが妥当っぽさ

**Comment by m1sk9** [comment]
そうやね. どっかのタイミングでやろうかな

**Comment by KisaragiEffective** [comment]
> https://github.com/rust-lang/mdBook/releases から引っ張ってくるのが妥当っぽさ

この手の欠点はバージョンを指定するとその更新を忘れることなので、立ち遅れないためにはRenovateでいい感じに抽出して更新させてやる必要がある

**Comment by m1sk9** [comment]
> この手の欠点はバージョンを指定するとその更新を忘れることなので、立ち遅れないためにはRenovateでいい感じに抽出して更新させてやる必要がある

何も考えないで latest を引っ張ってくるようにした (そんな壊れるような破壊的変更は来ないだろうという楽観)

**Comment by KisaragiEffective** [comment]
> > この手の欠点はバージョンを指定するとその更新を忘れることなので、立ち遅れないためにはRenovateでいい感じに抽出して更新させてやる必要がある
> 
> 
> 
> 何も考えないで latest を引っ張ってくるようにした (そんな壊れるような破壊的変更は来ないだろうという楽観)

latestにするとバージョンが固定されないので再現したくなったときに困る

**Comment by m1sk9** [comment]
それもそう. なんか考えるか...
