### ISSUE TITLE
デプロイに使用する mdbook のバージョンをコントロール出来るように

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/CommandReference#22]
> https://github.com/rust-lang/mdBook/releases から引っ張ってくるのが妥当っぽさ

この手の欠点はバージョンを指定するとその更新を忘れることなので、立ち遅れないためにはRenovateでいい感じに抽出して更新させてやる必要がある

_Originally posted by @KisaragiEffective in https://github.com/GiganticMinecraft/CommandReference/issues/19#issuecomment-2181931386_

**Comment by KisaragiEffective** [comment]
どうせ最新に追従するしかないんだから最新に追従するRenovateをauto-merge無効で組む
