### ISSUE TITLE
renovate が依存関係の更新に失敗している

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/CommandReference#26]
#25
> WARN: Error updating branch: update failure

ログは https://developer.mend.io/github/GiganticMinecraft/CommandReference/-/job/01910b45-ef1f-7b93-861f-f44003d9be5c で見れるが, なぜか **No log is available for this job** になっている

**Comment by m1sk9** [comment]
@KisaragiEffective 頼んだw

**Comment by KisaragiEffective** [comment]
@m1sk9 はぁ？しょうがねえな

**Comment by KisaragiEffective** [comment]
謎
問題のアプリを手動更新したら黙るかも

**Comment by m1sk9** [comment]
これね. 手動更新しても直らない

**Comment by m1sk9** [comment]
たぶんなおった
