### ISSUE TITLE
保護作成において方向を指定するコマンドの記述を追加

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/CommandReference#37]
> 保護の指定サイズを変えるコマンドで、
> expand [数値] 方角,向き : 指定した方向に[数値]マス広げる
> contract [数値] 方角,向き : 指定した方向に[数値]マス縮める
> shift [数値] 方角,向き : 指定した方向に[数値]マス移動する
> これらを追加してほしいです。
> 向き指定無しなら自分の向いてる方に、right left backなどでも方向指定できる旨をよろしくお願いします。

> 方角,向きを指定しない場合、me(自分から見て前向き)が自動で選ばれるというのも追加してほしいです。
> ### 自分の顔の向き基点
> me
> forward
> right
> left
> back
> up
> down
> 
> ### 方角
> north
> south
> west
> east

**Comment by KisaragiEffective** [comment]
これ本当にWGか…？と思ったけど便宜上WEのコマンドであれWGにまとめてんのか

**Comment by m1sk9** [comment]
> これ本当にWGか…？と思ったけど便宜上WEのコマンドであれWGにまとめてんのか

WorldEdit がプレイヤー向けコマンドじゃないからね. そうなってる.

**Comment by m1sk9** [comment]
`shift` は `default` (一般プレイヤー) の権限ノードでは使用できないので書かない
