### ISSUE TITLE
Webサイト側から動線誘導を行う

### ISSUE THREAD

**Issue by KisaragiEffective** [GiganticMinecraft/CommandReference#4]
blocked by ~~#1~~, ~~#5~~

**Comment by m1sk9** [comment]
GitHub Pages を使って静的にホスティングと考えているので seichi.click のDNSを設定したい

Cloudflare の権限が欲しい

**Comment by Lucky3028** [comment]
GitHubでInfra as a codeされているので、コミットするだけでDNS張れます

**Comment by Lucky3028** [comment]
https://github.com/GiganticMinecraft/seichi_infra/blob/main/terraform/cloudflare_dns_records.tf

**Comment by m1sk9** [comment]
> GitHubでInfra as a codeされているので、コミットするだけでDNS張れます

天才過ぎない？？？

**Comment by m1sk9** [comment]
とりあえずブロックされたIssueは全てクローズできたので、公式ホームページのコマンドリファレンスを置き換える形で対応する

(ただ、まだ試験段階であることにして既存のコマンドリファレンスはしばらくそのままにする)
