### ISSUE TITLE
Nextra への移植

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/CommandReference#6]
GitHub Pages での静的ホスティングでは Jekyll を使い簡易的なテーマを適用することができるが、コマンドリファレンスが膨大なためプレイヤーが目的のコマンドへ辿り着けるように検索機能がデフォルトでサポートされた Nextra へ移植することを検討する

- 参考: [GitHub PagesとJekyllについて](https://docs.github.com/ja/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)
- [Nextra – Next.js Static Site Generator](https://nextra.site/)

ただし、 Nextra が Next.js 上で動作する都合上デプロイは Cf Pages に限定されてしまう
[( Next.js を使う以上 Vercel が一番良いが、チームプランが洒落にならないくらい高価なので)](https://vercel.com/pricing)

**Comment by KisaragiEffective** [comment]
自分はメリットの割にデメリットが大きいと思っているのでマイグレーションする意義を見いだせない

* 元々Wixの低品質なWYSIWYGやレスポンシブ対応にロックインされるのが嫌ということが動機だったのにNextraを採用するとNextraのcaveatsにロックインされる危険性があると思っている
  * それこそ誰もメンテナンスできないということになりかねない
* 静的[^1]なものを静的のままにしておくというのは継続的な管理をする上で都合が良い
  * **この点だけで言うとJSX (を入力する任意のトランスパイラ) よりもWixが良い**
  * たかだか簡単なドキュメンテーションのためにJSXを書きたくない
  * 検索と引き換えにJavaScriptの混沌としたエコシステムのカルマや破壊的変更に付き合わされることを考えると分が合わない
* 検索してもらうなら<kbd>Ctrl</kbd> + <kbd>F</kbd>で良くない？
  * そもそも膨大って言うほどエントリ数が多くない。せいぜい数十個だし今後も多分そんなに増えない

[^1]: ここでいう静的とはCDN上などでトランスパイルした結果の出力に全てがバンドルされていたりJavaScriptが全く存在しないという定義ではなく、JSXやMDXからのトランスパイルを挟まないということ

**Comment by outductor** [comment]
何を採用するかは置いといて、 `ただし、 Nextra が Next.js 上で動作する都合上デプロイは Cf Pages に限定されてしまう` は大きな嘘です。

Ref. https://github.com/GiganticMinecraft/seichi_infra/blob/main/DEPLOYMENT.md#2-整地鯖の-kubernetes-上にデプロイする

**Comment by m1sk9** [comment]
@KisaragiEffective 

すでに移植進めてたけど、やってる間で移行する意味が無くなっていることに気づいたので普通にそのままでいいような気がする
