### ISSUE TITLE
誤字をCIで検知する仕組みの設定

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/CommandReference#9]
related: #10

**Comment by m1sk9** [comment]
有名なのはここらへん？
https://github.com/textlint/textlint

**Comment by KisaragiEffective** [comment]
@m1sk9 
週初めに建てられたissueのはじめのコメントが意味不明だったので書き換えた。仮に、#10 が原因だとしても、どちらも存在する名詞なので、存在するワードを存在しない文字列と取り違えた類型ではない。よって、その手の間違いはコミットするときに気をつける以外の選択肢はない。
※このコメントは存在するワードを存在しない文字列と取り違えてしまったときなどに落ちるCIのセットアップの必要性を否定するものではないことに注意。

**Comment by m1sk9** [comment]
textlint を採用したとしても Node.js を触る必要が出てくるなら私は嫌なので，人間が気をつけるということで
